inherit_from: .rubocop_todo.yml

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/20200508193804_create_accounts.rb'
    - 'db/migrate/20200508194052_create_transactions.rb'
    - 'db/migrate/20200509222431_rename_columns.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'spec/rails_helper.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Layout/LineLength:
  Max: 100
