# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf21cb480f0040a91820f54d68271f7c27fd41802eb6bb1142aa1fada7ef7ec71ffa45014a1f0c184f46dd90b2c6e73bd64be37781f84957e4ea932099494308

test:
  secret_key_base: fdc22c575d07493a0c4f74808d3af6234bfcaf9dc38266abcdbedef4e18b1ab984cb9c73e40ff988be23abb1c1e614a8190c9a61bbb357742bb9b2b7bf534c8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
